import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AdBanner from "./components/AdBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="container mx-auto flex flex-col lg:flex-row gap-8 py-8">
          <div className="container mx-auto py-4 lg:hidden">
          <AdBanner />
          </div>
          <aside className="w-1/5 hidden lg:block">
            <AdBanner />
          </aside>

          <main className="w-full lg:w-3/5">
            {children}
          </main>

          <aside className="w-1/5 hidden lg:block">
            <AdBanner />
          </aside>
          </div>
        <Footer />
      </body>
    </html>
  );
}
